### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by davidbsp** [Formal-Systems-Laboratory/ROSRV#2]
So, I am trying out ROSRV in Ubuntu 16.04 with ROS Kinetic.

I was able to follow all these steps:
https://github.com/Formal-Systems-Laboratory/rosmop/blob/master/INSTALL.md

And then when I compile ROSRV with catkin_make, following the instructions at: http://fsl.cs.illinois.edu/index.php/ROSRV, I get the following compilation error:

> $ catkin_make
> Base path: /home/robotcraft/ROSRV
> Source space: /home/robotcraft/ROSRV/src
> Build space: /home/robotcraft/ROSRV/build
> Devel space: /home/robotcraft/ROSRV/devel
> Install space: /home/robotcraft/ROSRV/install
> ####
> #### Running command: "make cmake_check_build_system" in "/home/robotcraft/ROSRV/build"
> ####
> ####
> #### Running command: "make -j1 -l1" in "/home/robotcraft/ROSRV/build"
> ####
> [  4%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/main.cpp.o
> [  9%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/rvmonitor.cpp.o
> [ 13%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcClient.cpp.o
> [ 18%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcServerConnection.cpp.o
> [ 22%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcServerMethod.cpp.o
> [ 27%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcSocket.cpp.o
> [ 31%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcServer.cpp.o
> [ 36%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcSource.cpp.o
> [ 40%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/xmlrpcpp/XmlRpcDispatch.cpp.o
> [ 45%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/rv/xmlrpc_manager.cpp.o
> [ 50%] Building CXX object RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/rv/connection_manager.cpp.o
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp: In member function ‘void rv::ConnectionManager::start()’:
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:56:14: **error**: no match for ‘operator=’ (operand types are ‘boost::signals::connection’ and ‘boost::signals2::connection’)
>    poll_conn_ = poll_manager_->addPollThreadListener(boost::bind(&ConnectionMana
>               ^
> In file included from /home/robotcraft/ROSRV/src/RVMaster/include/rv/connection_manager.h:9:0,
>                  from /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:1:
> /usr/include/boost/signals/connection.hpp:90:19: note: candidate: boost::signals::connection& boost::signals::connection::operator=(const boost::signals::connection&)
>        connection& operator=(const connection& other) ;
>                    ^
> /usr/include/boost/signals/connection.hpp:90:19: note:   no known conversion for argument 1 from ‘boost::signals2::connection’ to ‘const boost::signals::connection&’
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp: In member function ‘void rv::ConnectionManager::shutdown()’:
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:95:53: **error**: no matching function for call to ‘ros::PollManager::removePollThreadListener(boost::signals::connection&)’
>    poll_manager_->removePollThreadListener(poll_conn_);
>                                                      ^
> In file included from /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:3:0:
> /opt/ros/kinetic/include/ros/poll_manager.h:59:8: note: candidate: void ros::PollManager::removePollThreadListener(boost::signals2::connection)
>    void removePollThreadListener(boost::signals2::connection c);
>         ^
> /opt/ros/kinetic/include/ros/poll_manager.h:59:8: note:   no known conversion for argument 1 from ‘boost::signals::connection’ to ‘boost::signals2::connection’
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp: In member function ‘bool rv::ConnectionManager::onConnectionHeaderReceived(const ConnectionPtr&, const ros::Header&)’:
> /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:205:69: **error**: invalid new-expression of abstract class type ‘rv::TransportSubscriberLink’
>      TransportSubscriberLinkPtr sub_link(new TransportSubscriberLink());
>                                                                      ^
> In file included from /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:5:0:
> /home/robotcraft/ROSRV/src/RVMaster/include/rv/transport_subscriber_link.h:15:19: note:   because the following virtual functions are pure within ‘rv::TransportSubscriberLink’:
>  class ROSCPP_DECL TransportSubscriberLink : public ros::SubscriberLink
>                    ^
> In file included from /home/robotcraft/ROSRV/src/RVMaster/include/rv/transport_subscriber_link.h:5:0,
>                  from /home/robotcraft/ROSRV/src/RVMaster/src/rv/connection_manager.cpp:5:
> /opt/ros/kinetic/include/ros/subscriber_link.h:77:23: note: 	virtual std::__cxx11::string ros::SubscriberLink::getTransportInfo()
>    virtual std::string getTransportInfo() = 0;
>                        ^
> RVMaster/CMakeFiles/rvmaster_rosmaster.dir/build.make:302: recipe for target 'RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/rv/connection_manager.cpp.o' failed
> make[2]: *** [RVMaster/CMakeFiles/rvmaster_rosmaster.dir/src/rv/connection_manager.cpp.o] **Error** 1
> CMakeFiles/Makefile2:825: recipe for target 'RVMaster/CMakeFiles/rvmaster_rosmaster.dir/all' failed
> make[1]: *** [RVMaster/CMakeFiles/rvmaster_rosmaster.dir/all] **Error** 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] **Error** 2
> Invoking "make -j1 -l1" failed

Is this an expectable error because I am using ROS Kinetic (instead of Groovy) and Ubuntu 16.04 (instead of 12.04) ? Thank you for the insight.

**Comment by ghost** [comment]
Having the same setup as you (Ubuntu 16.04 and ROS Kinetic) and experiencing the same problems with compilation. From the last commit date (March 5, 2016) I get the feeling this package isn't being maintained anymore, sadly. Seems like I'll have to find another implementation of runtime verification for ROS. Or maybe even build one myself.

**Comment by msaxena2** [comment]
This is fixed now.
